In [16]:
import pandas as pd
import os

ROOT_DIR = os.getcwd()  # .../somalogic
file = os.path.join(ROOT_DIR, 'data', 'Changes_severity.csv')

In [17]:
df = pd.read_csv(file)
df

,anonymized_patient_id,SubjectID,A3_v2,A2_v2,New_severity,change_A3,change_A2,change_New_severity,date_sampling
0,CHUM_1,03201-20_CHUM,1,1,3,1,1,1,2020-04-07
1,CHUM_1,03211-20_CHUM,1,1,3,1,1,1,2020-04-09
2,CHUM_10,04271-20_CHUM,1,1,3,1,1,1,2020-04-16
3,CHUM_10,03216-20_CHUM,1,1,3,1,1,1,2020-04-14
4,CHUM_10,03208-20_CHUM,1,1,3,1,1,1,2020-04-09
...,...,...,...,...,...,...,...,...,...
1033,JGH_95,VAP03374-20,0,0,0,2,2,2,2020-04-12
1034,JGH_96,VAP03414-20,0,0,0,1,1,1,2020-04-10
1035,JGH_96,VAP11585-20,0,0,0,1,1,1,2020-07-30
1036,JGH_98,VAP03412-20,0,0,0,1,1,1,2020-04-10
1037,JGH_99,VAP03411-20,0,0,0,1,1,1,2020-04-10

### Group by Patient ID and then sort date sampling in ascending order

In [38]:
df_sorted = df.groupby (["anonymized_patient_id"], as_index=False). apply (lambda x: x.sort_values(["date_sampling"]))
df_sorted

         anonymized_patient_id      SubjectID  A3_v2  A2_v2  New_severity  \
0   0                   CHUM_1  03201-20_CHUM      1      1             3
    1                   CHUM_1  03211-20_CHUM      1      1             3
1   4                  CHUM_10  03208-20_CHUM      1      1             3
    3                  CHUM_10  03216-20_CHUM      1      1             3
    2                  CHUM_10  04271-20_CHUM      1      1             3
...                        ...            ...    ...    ...           ...
499 1032                JGH_95    VAP04598-20      0      0             0
500 1034                JGH_96    VAP03414-20      0      0             0
    1035                JGH_96    VAP11585-20      0      0             0
501 1036                JGH_98    VAP03412-20      0      0             0
502 1037                JGH_99    VAP03411-20      0      0             0

          change_A3  change_A2  change_New_severity date_sampling
0   0             1          1                    1    2020-04-07
    1             1          1                    1    2020-04-09
1   4             1          1                    1    2020-04-09
    3             1          1                    1    2020-04-14
    2             1          1                    1    2020-04-16
...             ...        ...                  ...           ...
499 1032          2          2                    2    2020-04-17
500 1034          1          1                    1    2020-04-10
    1035          1          1                    1    2020-07-30
501 1036          1          1                    1    2020-04-10
502 1037          1          1                    1    2020-04-10

[1038 rows x 9 columns]

In [39]:
# Get subset rows with a change in A3_v2 case to control using 'change_A3' 
df_change = df_sorted[df_sorted['change_A3'] > 1]  # 1 = no change in A3_v2 case-control, 2 = change
df_change

         anonymized_patient_id      SubjectID  A3_v2  A2_v2  New_severity  \
8   13                CHUM_107  07713-20_CHUM      1      0             1
    14                CHUM_107  07756-20_CHUM      0      0             0
20  37                CHUM_120  07741-20_CHUM      1      0             1
    39                CHUM_120  07748-20_CHUM      1      1             2
    38                CHUM_120  09204-20_CHUM      1      0             1
...                        ...            ...    ...    ...           ...
494 1016                JGH_88    VAP03392-20      1      0             1
    1017                JGH_88    VAP04599-20      0      0             0
499 1031                JGH_95    VAP03415-20      1      1             3
    1033                JGH_95    VAP03374-20      0      0             0
    1032                JGH_95    VAP04598-20      0      0             0

          change_A3  change_A2  change_New_severity date_sampling
8   13            2          1                    2    2020-05-15
    14            2          1                    2    2020-05-28
20  37            2          2                    2    2020-05-23
    39            2          2                    2    2020-05-26
    38            2          2                    2    2020-05-29
...             ...        ...                  ...           ...
494 1016          2          1                    2    2020-04-12
    1017          2          1                    2    2020-04-20
499 1031          2          2                    2    2020-04-10
    1033          2          2                    2    2020-04-12
    1032          2          2                    2    2020-04-17

[233 rows x 9 columns]

In [44]:
# get difference in change in each group
df_change['A3_v2_diff'] = df_change.groupby(["anonymized_patient_id"])['A3_v2'].diff()

/home/csu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [45]:
df_change

         anonymized_patient_id      SubjectID  A3_v2  A2_v2  New_severity  \
8   13                CHUM_107  07713-20_CHUM      1      0             1
    14                CHUM_107  07756-20_CHUM      0      0             0
20  37                CHUM_120  07741-20_CHUM      1      0             1
    39                CHUM_120  07748-20_CHUM      1      1             2
    38                CHUM_120  09204-20_CHUM      1      0             1
...                        ...            ...    ...    ...           ...
494 1016                JGH_88    VAP03392-20      1      0             1
    1017                JGH_88    VAP04599-20      0      0             0
499 1031                JGH_95    VAP03415-20      1      1             3
    1033                JGH_95    VAP03374-20      0      0             0
    1032                JGH_95    VAP04598-20      0      0             0

          change_A3  change_A2  change_New_severity date_sampling  A3_v2_diff
8   13            2          1                    2    2020-05-15         NaN
    14            2          1                    2    2020-05-28        -1.0
20  37            2          2                    2    2020-05-23         NaN
    39            2          2                    2    2020-05-26         0.0
    38            2          2                    2    2020-05-29         0.0
...             ...        ...                  ...           ...         ...
494 1016          2          1                    2    2020-04-12         0.0
    1017          2          1                    2    2020-04-20        -1.0
499 1031          2          2                    2    2020-04-10         NaN
    1033          2          2                    2    2020-04-12        -1.0
    1032          2          2                    2    2020-04-17         0.0

[233 rows x 10 columns]

In [48]:
df_filtered = df_change[df_change['A3_v2_diff'] > 0]  # only keep patients where change is greater than 1

In [49]:
df_filtered

,,anonymized_patient_id,SubjectID,A3_v2,A2_v2,New_severity,change_A3,change_A2,change_New_severity,date_sampling,A3_v2_diff
152,302,JGH_15,VAP03079-20,1,0,1,2,1,2,2020-04-08,1.0
251,495,JGH_329,VAP06196-20,1,0,1,2,1,2,2020-05-01,1.0
375,760,JGH_594,VAP07926-20,1,0,1,2,1,2,2020-05-15,1.0
388,785,JGH_614,VAP08357-20,1,0,1,2,1,2,2020-05-17,1.0
400,811,JGH_642,VAP08348-20,1,0,1,2,1,2,2020-05-18,1.0
458,927,JGH_778,VAP09623-20,1,1,3,2,2,2,2020-05-31,1.0
475,969,JGH_798,VAP09607-20,1,0,1,2,2,2,2020-06-07,1.0
478,979,JGH_800,VAP09606-20,1,0,1,2,1,2,2020-06-08,1.0
492,1012,JGH_84,VAP03396-20,1,1,3,2,2,2,2020-04-12,1.0

In [53]:
patients = df_filtered['anonymized_patient_id'].tolist()  # get the patients in list 
patients

['JGH_15',
 'JGH_329',
 'JGH_594',
 'JGH_614',
 'JGH_642',
 'JGH_778',
 'JGH_798',
 'JGH_800',
 'JGH_84']

In [60]:
df_final = df_sorted[df_sorted['anonymized_patient_id'].isin(patients)]  # use patients list to get all samples of those patients
df_final

         anonymized_patient_id    SubjectID  A3_v2  A2_v2  New_severity  \
152 300                 JGH_15  VAP02615-20      0      0             0
    302                 JGH_15  VAP03079-20      1      0             1
    301                 JGH_15  VAP11145-20      0      0             0
251 496                JGH_329  VAP05326-20      0      0             0
    495                JGH_329  VAP06196-20      1      0             1
    494                JGH_329  VAP06830-20      0      0             0
375 759                JGH_594  VAP07978-20      0      0             0
    760                JGH_594  VAP07926-20      1      0             1
    758                JGH_594  VAP08340-20      1      0             1
388 784                JGH_614  VAP07958-20      0      0             0
    785                JGH_614  VAP08357-20      1      0             1
    783                JGH_614  VAP08770-20      0      0             0
400 810                JGH_642  VAP08380-20      0      0             0
    811                JGH_642  VAP08348-20      1      0             1
    812                JGH_642  VAP08738-20      0      0             0
458 928                JGH_778  VAP08996-20      0      0             0
    927                JGH_778  VAP09623-20      1      1             3
    929                JGH_778  VAP09609-20      1      1             3
475 971                JGH_798  VAP09670-20      0      0             0
    969                JGH_798  VAP09607-20      1      0             1
    970                JGH_798  VAP05289-20      1      1             3
478 978                JGH_800  VAP09668-20      0      0             0
    979                JGH_800  VAP09606-20      1      0             1
    977                JGH_800  VAP06188-20      0      0             0
492 1011                JGH_84  VAP03426-20      0      0             0
    1012                JGH_84  VAP03396-20      1      1             3

          change_A3  change_A2  change_New_severity date_sampling
152 300           2          1                    2    2020-04-06
    302           2          1                    2    2020-04-08
    301           2          1                    2    2020-07-16
251 496           2          1                    2    2020-04-27
    495           2          1                    2    2020-05-01
    494           2          1                    2    2020-05-06
375 759           2          1                    2    2020-05-13
    760           2          1                    2    2020-05-15
    758           2          1                    2    2020-05-24
388 784           2          1                    2    2020-05-14
    785           2          1                    2    2020-05-17
    783           2          1                    2    2020-05-21
400 810           2          1                    2    2020-05-16
    811           2          1                    2    2020-05-18
    812           2          1                    2    2020-05-23
458 928           2          2                    2    2020-05-27
    927           2          2                    2    2020-05-31
    929           2          2                    2    2020-06-05
475 971           2          2                    2    2020-06-03
    969           2          2                    2    2020-06-07
    970           2          2                    2    2020-06-12
478 978           2          1                    2    2020-06-03
    979           2          1                    2    2020-06-08
    977           2          1                    2    2020-06-12
492 1011          2          2                    2    2020-04-10
    1012          2          2                    2    2020-04-12

### Add days_symptom_update3 to last column

In [62]:
file = os.path.join(ROOT_DIR, 'data', 'Proteomic_new_severity.csv')

proteomic_severity = pd.read_csv(file)
proteomic_severity

,SubjectID,A2_v2,A3_v2,New_severity,anonymized_patient_id,Controls_without_viral_infection_stringent,Days_symptom_update3,ProcessTime,A2_new,anonymized_patient_id.y,...,hosp_bleeding,hosp_hepatic,covid19_test,covid19_test_date,covid19_first_symptoms_date,com_cancer,A2,B1,B2,C2
0,03201-20_CHUM,1,1,3,CHUM_1,0,9.0,0.83,1,CHUM_1,...,NaN,0,1,2020-03-29,2020-03-29,0.0,1,1,1,1
1,03202-20_CHUM,1,0,1,CHUM_5,0,13.0,2.83,1,CHUM_5,...,NaN,1,1,2020-03-31,2020-03-26,0.0,0,1,1,1
2,03203-20_CHUM,1,1,3,CHUM_6,0,17.0,5.17,1,CHUM_6,...,NaN,1,1,2020-04-05,2020-03-22,0.0,1,1,1,1
3,03204-20_CHUM,1,1,3,CHUM_7,0,11.0,5.42,1,CHUM_7,...,NaN,1,1,2020-04-06,2020-03-28,0.0,1,1,1,1
4,03205-20_CHUM,0,0,0,CHUM_8,0,2.0,6.90,0,CHUM_8,...,NaN,0,0,NaN,NaN,0.0,0,-1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,VAP14505-20,0,0,0,JGH_581,0,106.0,2.72,0,JGH_581,...,0.0,0,1,2020-05-20,2020-05-06,NaN,0,1,1,1
1034,VAP14510-20,0,0,0,JGH_784,0,99.0,5.00,0,JGH_784,...,0.0,1,1,2020-07-21,2020-05-12,NaN,0,1,1,1
1035,VAP14511-20,0,0,0,JGH_808,0,68.0,3.83,0,JGH_808,...,0.0,1,1,2020-06-16,2020-06-13,NaN,0,1,1,1
1036,VAP14514-20,0,0,0,JGH_135,0,138.0,1.50,1,JGH_135,...,0.0,1,1,2020-05-06,2020-04-03,NaN,1,1,1,1
1037,VAP14516-20,0,0,0,JGH_697,0,103.0,2.83,1,JGH_697,...,0.0,0,1,2020-05-15,2020-05-08,NaN,1,1,1,1

In [66]:
to_merge = proteomic_severity[['SubjectID', 'Days_symptom_update3']]
to_merge

          SubjectID  Days_symptom_update3
0     03201-20_CHUM                   9.0
1     03202-20_CHUM                  13.0
2     03203-20_CHUM                  17.0
3     03204-20_CHUM                  11.0
4     03205-20_CHUM                   2.0
...             ...                   ...
1033    VAP14505-20                 106.0
1034    VAP14510-20                  99.0
1035    VAP14511-20                  68.0
1036    VAP14514-20                 138.0
1037    VAP14516-20                 103.0

[1038 rows x 2 columns]

In [68]:
df_final_final = pd.merge(df_final, to_merge, on='SubjectID')
df_final_final

,anonymized_patient_id,SubjectID,A3_v2,A2_v2,New_severity,change_A3,change_A2,change_New_severity,date_sampling,Days_symptom_update3
0,JGH_15,VAP02615-20,0,0,0,2,1,2,2020-04-06,9.0
1,JGH_15,VAP03079-20,1,0,1,2,1,2,2020-04-08,11.0
2,JGH_15,VAP11145-20,0,0,0,2,1,2,2020-07-16,110.0
3,JGH_329,VAP05326-20,0,0,0,2,1,2,2020-04-27,4.0
4,JGH_329,VAP06196-20,1,0,1,2,1,2,2020-05-01,8.0
5,JGH_329,VAP06830-20,0,0,0,2,1,2,2020-05-06,13.0
6,JGH_594,VAP07978-20,0,0,0,2,1,2,2020-05-13,7.0
7,JGH_594,VAP07926-20,1,0,1,2,1,2,2020-05-15,9.0
8,JGH_594,VAP08340-20,1,0,1,2,1,2,2020-05-24,18.0
9,JGH_614,VAP07958-20,0,0,0,2,1,2,2020-05-14,4.0
10,JGH_614,VAP08357-20,1,0,1,2,1,2,2020-05-17,7.0
11,JGH_614,VAP08770-20,0,0,0,2,1,2,2020-05-21,11.0
12,JGH_642,VAP08380-20,0,0,0,2,1,2,2020-05-16,5.0
13,JGH_642,VAP08348-20,1,0,1,2,1,2,2020-05-18,7.0
14,JGH_642,VAP08738-20,0,0,0,2,1,2,2020-05-23,12.0
15,JGH_778,VAP08996-20,0,0,0,2,2,2,2020-05-27,7.0
16,JGH_778,VAP09623-20,1,1,3,2,2,2,2020-05-31,11.0
17,JGH_778,VAP09609-20,1,1,3,2,2,2,2020-06-05,16.0
18,JGH_798,VAP09670-20,0,0,0,2,2,2,2020-06-03,3.0
19,JGH_798,VAP09607-20,1,0,1,2,2,2,2020-06-07,7.0
20,JGH_798,VAP05289-20,1,1,3,2,2,2,2020-06-12,12.0
21,JGH_800,VAP09668-20,0,0,0,2,1,2,2020-06-03,0.0
22,JGH_800,VAP09606-20,1,0,1,2,1,2,2020-06-08,5.0
23,JGH_800,VAP06188-20,0,0,0,2,1,2,2020-06-12,9.0
24,JGH_84,VAP03426-20,0,0,0,2,2,2,2020-04-10,9.0
25,JGH_84,VAP03396-20,1,1,3,2,2,2,2020-04-12,11.0

In [72]:
df_final_final.to_csv('A3_v2_control_to_case.csv', index=False)